/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.projecteuler.tm700

import org.assertj.core.api.Assertions.assertThat
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe

internal class AppTest : Spek({
    describe("AppTest") {
        it("testProblem006") {
            assertThat(25_164_150).isEqualTo(Problem006().solve())
        }

        it("testProblem008") {
            assertThat(23514624000L).isEqualTo(Problem008().solve())
        }

        it("testProblem009") {
            assertThat(31875000).isEqualTo(Problem009().solve())
        }

        it("testProblem099") {
            assertThat(709).isEqualTo(Problem099().solve())
        }
    }
})
