/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package projecteuler.kt

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun testProblem006() {
        assertEquals(25_164_150, Problem006().solve())
    }

    @Test fun testProblem008() {
        assertEquals(23514624000L, Problem008().solve())
    }

    @Test fun testProblem009() {
        assertEquals(31875000, Problem009().solve())
    }

    @Test fun testProblem099() {
     assertEquals(709, Problem099().solve())
    }
}
