// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms
// will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.

package net.projecteuler.tm700

class Problem002(val size: Int = 4_000_000) {
    private fun fibs(): Sequence<Int> {
        return generateSequence(Pair(1, 2), {
            Pair(it.second, it.first + it.second)
        }).map { it.first }
    }

    fun solve(): Int = fibs().takeWhile { it < size }
            .filter { it % 2 == 0 }
            .sum()
}
