/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package projecteuler.kt

fun main() {
    println("Problem001: " + Problem001().solve())
    println("Problem002: " + Problem002().solve())
    println("Problem004: " + Problem004().solve())
    println("Problem005: " + Problem005().solve())
    println("Problem006: " + Problem006().solve())
    println("Problem008: " + Problem008().solve())
}
