/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package projecteuler.kt

class Problem001(val size: Int = 999) {
    fun solve(): Int {
        return (1..size)
                .filter { it % 3 == 0 || it % 5 == 0 }
                .reduce { a, b -> a + b }
    }
}
